apiVersion: batch/v1
kind: Job
metadata:
  name: $JOB_NAME
  labels:
    app: organoid-hmm
    user: $USER
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: hmm-worker
        image: atspaeth/organoid-hmm
        env:
          - name: S3_USER
            value: $USER
          - name: ENDPOINT
            value: http://rook-ceph-rgw-nautiluss3.rook
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /root/.aws
            name: prp-s3-credentials
        resources:
          requests:
            cpu: 1
            memory: "12Gi"
            nvidia.com/gpu: 0
          limits:
            cpu: 1
            memory: "16Gi"
            nvidia.com/gpu: 0
        command: ["python", "hmm_worker.py"]
      restartPolicy: Never
      volumes:
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
