apiVersion: batch/v1
kind: Job
metadata:
  name: $JOB_NAME
  labels:
    app: organoid-hmm
    user: $S3_USER
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: ${CLEAN_NAME}
        image: ${CONTAINER_IMAGE}
        env:
          - name: S3_USER
            value: $S3_USER
          - name: ENDPOINT
            value: https://s3.braingeneers.gi.ucsc.edu
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /root/.aws
            name: prp-s3-credentials
        resources:
          requests:
            cpu: 1
            memory: "${NRP_MEMORY_GI}Gi"
            nvidia.com/gpu: 0
          limits:
            cpu: 1
            memory: "${NRP_MEMORY_LIMIT_GI}Gi"
            nvidia.com/gpu: 0
        command: ["python", "${SCRIPT_NAME}.py"]
      restartPolicy: Never
      volumes:
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
