apiVersion: batch/v1
kind: Job
metadata:
  name: atspaeth-hmms-$HMM_DATA_SOURCE-$HMM_EXPERIMENT-$HMM_BIN_SIZE_MS-$HMM_K_RANGE-$HMM_METHOD
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: fit-hmms
        image: atspaeth/organoid-hmm
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /root/.aws
            name: prp-s3-credential
        resources:
          limits:
            cpu: 1
            memory: "16Gi"
            nvidia.com/gpu: 0
        command: ["python", "stash_hmms.py"]
        args:
          - $HMM_DATA_SOURCE
          - $HMM_EXPERIMENT
          - $HMM_BIN_SIZE_MS
          - $HMM_K_RANGE
          - $HMM_METHOD
      restartPolicy: Never
      volumes:
        - name: prp-s3-credential
          secret:
            secretName: prp-s3-credential
